spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mylab
        username: postgres
        password: 1234
    jpa :
        properties:
            hibernate:
                ddl-auto : update
                jdbc.lob.non_contextual_creation : true
                dialect : org.hibernate.dialect.PostgreSQLDialect



